export const ALLOWED_ICONS = [
  "✦",
  "◈",
  "⌘",
  "⟡",
  "▲",
  "◆",
  "☽",
  "✿",
  "⊕",
  "⟢",

] as const;

export const SHUFFLE_NAMES = [
  "quiet ghost",
  "warm signal",
  "darija kid",
  "atlas wanderer",
  "shell poet",
  "lunar dev",
  "kif kif",
  "pixel sage",
  "maghreb echo",
  "void tender",
  "neon nomad",
  "terracotta",
  "baraka wave",
  "late night push",
  "still water",
  "404 heart",
  "soft kernel",
  "open source soul",
  "refind user",
  "local llm",
  "gnome enjoyer",
  "fedora kid",
  "mono type",
  "serif ghost",
  "warm stone",
  "3am deploy",
  "blinking cursor",
  "dark mode",
  "offline first",
  "signal lost",
  "desert dev",
  "old hardware",
  "small batch",
  "handmade web",
  "no ads",
  "clean cache",
  "ب",
  "ⵎ",
  "koko fan",
  "7amdi reader"
] as const;
